Getting and Cleaning Data Project
========================================================

Class:      https://class.coursera.org/getdata-002  
Student:    Jeanne-Anne Jensen, jana.jensen@comcast.net  

Assignment Instructions
-------------------------

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.  

One of the most exciting areas in all of data science right now is wearable computing - see for example [this article](http://www.insideactivitytracking.com/data-science-activity-tracking-and-the-battle-for-the-worlds-top-sports-brand/). Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained: 

[http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

Here are the data for the project: 

[https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

You should create one R script called run_analysis.R that does the following.   
1. Merges the training and the test sets to create one data set.  
2. Extracts only the measurements on the mean and standard deviation for each measurement.   
3. Uses descriptive activity names to name the activities in the data set  
4. Appropriately labels the data set with descriptive activity names.   
5. Creates a second, independent tidy data set with the average of each variable for each activity and each subject.   

Human Activity Recognition Using Smartphones Data Set 
-------------------------
**Abstract:** Human Activity Recognition database built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.

 Summary  |  Value
--- | ---
Data Set Characteristics: | Multivariate, Time-Series
Attribute Characteristics: | N/A
Associated Tasks: | Classification, Clustering
Number of Instances: | 10299
Number of Attributes: | 561
Missing Values? | N/A
Area: | Computer
Date Donated: | 2012-12-10
Number of Web Hits: | 76879


**Source:**

Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.  
Smartlab - Non Linear Complex Systems Laboratory  
DITEN - UniversitÃ  degli Studi di Genova, Genoa I-16145, Italy.  
activityrecognition '@' smartlab.ws  
www.smartlab.ws  

### Human Activity Recognition Using Smartphones Dataset (Version 1.0)

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 

#### For each record it is provided:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

#### The dataset includes the following files:

- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

#### The following files are available for the train and test data. Their descriptions are equivalent. 

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

- 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

- 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 

#### Notes: 

- Features are normalized and bounded within [-1,1].
- Each feature vector is a row on the text file.

For more information about this dataset contact: activityrecognition@smartlab.ws

#### License:

Use of this dataset in publications must be acknowledged by referencing the following publication [1] 

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.

Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita. November 2012.

Exploring the data
-------------------------
```{r}
################
# Set-Up
################

# set up location for project files
datadir <- "~/GitHub/datasciencecoursera-GetData-PA"
if(!file.exists(datadir)){dir.create(datadir)}
setwd(datadir)

# download data for the project
fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
zipfile <- "getdata-projectfiles-UCI HAR Dataset.zip"
if(!file.exists(zipfile)){download.file(fileUrl,destfile=zipfile)}
unzip(zipfile, files=NULL, list=TRUE) # see the list of available files

# extract just the files we want into our datadir
wantfiles <- c("UCI HAR Dataset/train/X_train.txt",        # training set
               "UCI HAR Dataset/train/y_train.txt",        # training labels
               "UCI HAR Dataset/train/subject_train.txt",  # training subjects
               "UCI HAR Dataset/test/X_test.txt",          # test set
               "UCI HAR Dataset/test/y_test.txt",          # test labels
               "UCI HAR Dataset/test/subject_test.txt",    # test subjects
               "UCI HAR Dataset/activity_labels.txt",      # activity labels
               "UCI HAR Dataset/features.txt")             # feature decodes
unzip(zipfile, files=wantfiles, junkpaths=TRUE, list=FALSE)
list.files(datadir)

################
# Examine data
################

# how many rows in total
trainLines <- length(readLines("X_train.txt"))  # how many rows in source file
testLines  <- length(readLines("X_test.txt"))   # how many rows in source file
c(trainLines,testLines)

# load first few rows of each
trainData  <- read.table("X_train.txt",nrows=5) # just a few rows of data
testData   <- read.table("X_test.txt" ,nrows=5)
trainLbls  <- read.table("Y_train.txt")         # all rows of labels
testLbls   <- read.table("Y_test.txt" )
trainSubs  <- read.table("subject_train.txt")
testSubs   <- read.table("subject_test.txt")
actvtyLbls <- read.table("activity_labels.txt")
features   <- read.table("features.txt")

# see what we've got
names(trainData)        # 561 vars
str(trainData[,1:10])   # all numbers
str(trainLbls)          # 7352 obs of 1 var, one for each row in data
table(trainLbls)        # var values are 1:6
str(trainSubs)          # 7352 obs of 1 var, one for each row in data
table(trainSubs)        # 21 subjects w/300+ rows each

names(testData)         # same as trainData
str(testData[,1:10])    # 561 vars, all numbers
str(testLbls)           # 2947 obs of 1 var, one for each row in data
table(testLbls)         # var values are 1:6
str(testSubs)           # 2947 obs of 1 var, one for each row in data
table(testSubs)         # 9 subjects w/300+ rows each (no overlap w/train)

actvtyLbls              # decodes the 6 labels

str(features)           # 561 obs of 2 vars, 2nd is the actual feature names

################
# see whether we've correctly inferred how to put the data together
################

# apply feature names to column headers
names(trainData) <- features[,2]
names(testData)  <- features[,2]

# add subjects to data
trainData$sub <- trainSubs[1:5,1]
testData$sub  <- testSubs[1:5,1]

# add labels to data
trainData$lbl <- trainLbls[1:5,1]
testData$lbl  <- testLbls[1:5,1]

# identify which rows came from which data set
trainData$src <- rep("train",nrow(trainData))
testData$src  <- rep("test",nrow(testData))

# combine the two data sets into one
allData <- rbind(trainData,testData)

# apply the activity labels
names(actvtyLbls) <- c("lbl","lbl_name")
library(plyr)
allData2 <- arrange(join(allData,actvtyLbls),lbl)

# summarize the data
meltData <- melt(meanstdData,
                 id=c("sub","activity"),
                 na.rm=TRUE)
aggData <- dcast(meltData,       # input data
                 sub + activity  # one row per each value
                 ~ variable,     # one col for each value
                 mean)           # how to aggregate

# let's see what we've got
aggData
```
